export const SET_EXPLORE_OR_FOCUS = "SET_EXPLORE_OR_FOCUS"
export const PUT_IMAGES_FROM_BACK_TO_FRONT = "PUT_IMAGES_FROM_BACK_TO_FRONT"
export const SET_FOCUSED_ITEM = "SET_FOCUSED_ITEM"
export const SET_RECOMS = "SET_RECOMS"

